---
title: "Untitled"
author: "Hans"
date: "10/27/2019"
output: html_document
---




```{r}
stocks <- tibble (
  year  = c(2015,2015,2015,2015,2016,2016,2016), 
  qtr =c( 1, 2, 3, 4, 2, 3, 4), 
  return=c(1.88,0.59,0.35, NA,0.92,0.17,2.66)
)

stocks

stocks %>%
  spread(year, return)

stocks %>%
  spread(year, return) %>%
  gather(year, return, `2015`:`2016`, na.rm = TRUE)

stocks %>%
      complete(year, qtr)

```


```{r}
treatment <- tribble(
  ~ person, ~ treatment, ~response, 
  "Derrick Whitmore", 1, 7,
  NA, 2, 10,
  NA, 3, 9, 
  "Katherine Burke", 1, 4
)

treatment

treatment %>%
  fill(person)
```


```{r}
who

who1 <- who %>% 
  gather(new_sp_m014:newrel_f65, 
         key = "key", 
         value = "cases",
         na.rm = TRUE)

who1

who1 %>%
  count(key)

who2 <- who1 %>%
  mutate(key = stringr::str_replace(key, "newrel", "new_rel"))

who2


who2 %>% 
  group_by (key) %>% 
  summarise (n = n()) 

who3 <- who2 %>%
  separate(key, c("new", "type", "sexage"), sep = "_")

who3

who3 %>%
  count(new)

who4 <- who3 %>%
  select (-new, -iso2, -iso3)

who4

who5 <- who4 %>% 
  separate(sexage, c("sex", "age"), sep = 1)

who5

count(who5, age)
count(who5,sex)
```



